
package com.techdata.carshop.clientWs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceImpl", targetNamespace = "http://impl.service.carshop.mycompany.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.techdata.carshop.clientWs.PartArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public PartArray getAllPartsByManufacturer(
        @WebParam(name = "arg0", partName = "arg0")
        Manufacturer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.techdata.carshop.clientWs.PartArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public PartArray getAllPartsBySystem(
        @WebParam(name = "arg0", partName = "arg0")
        CarSystem arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.techdata.carshop.clientWs.Part
     */
    @WebMethod
    @WebResult(partName = "return")
    public Part getPartById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns com.techdata.carshop.clientWs.PartArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public PartArray getAllParts();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.techdata.carshop.clientWs.CarSystem
     */
    @WebMethod
    @WebResult(partName = "return")
    public CarSystem getSystemById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns com.techdata.carshop.clientWs.CarSystemArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public CarSystemArray getAllSystems();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.techdata.carshop.clientWs.Member
     */
    @WebMethod
    @WebResult(partName = "return")
    public Member getMemberById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns com.techdata.carshop.clientWs.MemberArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public MemberArray getAllMembers();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.techdata.carshop.clientWs.Deal
     */
    @WebMethod
    @WebResult(partName = "return")
    public Deal getDealById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.techdata.carshop.clientWs.DealArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public DealArray getDealsByMember(
        @WebParam(name = "arg0", partName = "arg0")
        Member arg0);

}
